# -*- coding: utf-8 -*-
"""Test File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSkYtYtjv5U1Pu4VZuuarZEENRO3hHqY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

"""Data Loading"""

data = pd.read_csv('train.csv')

data

data.info()

data.describe()

data.plot.line(y = 'num_orders', x = 'center_id')

del data['homepage_featured']

data.info()

"""Model Creation"""

x = data.drop('num_orders', axis = 1)
y = data['num_orders']
scaler = StandardScaler()
scaled_data = (x,y)

x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state= 42)

model = LinearRegression()
model.fit(x_train, y_train)

"""Predictions

"""

y_pred = model.predict(x_test)

y_pred

mse = mean_squared_error(x_test,y_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)



prediction = pd.DataFrame(y_pred, columns=['predicted_num_orders'])

prediction.to_csv('10Week_predictions.csv', index=False)

